# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
  branches:
    include:
    - master

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- script: |
   npm ci
   npm install
   npm run build --if-present
   npm test
   
  displayName: 'npm ci, install, build, test'

- script: |
   npm pack
   mkdir tmp/ && cp *.tgz tmp/
  displayName: 'npm pack'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/tmp'


